
data:
  raw_data_path: "./data/raw/"
  processed_data_path: "./data/processed/"
  model_save_path: "./models/model.pkl"

model:
  type: "RandomForest"
  parameters:
    n_estimators: 100
    max_depth: 10
